###obtener todos los productos
GET http://localhost:62299/admins

###Create an admin
POST http://localhost:62299/admins
Content-Type: application/json

{
  "name":"Carlos Andres Noreña Vargas",
  "email":"carlos1997704@gmail.com",
  "password":"123456",
  "idType":"National ID",
  "idNumber":"1000897044",
  "phone":"3000000000"
}

###Login
POST http://localhost:62299/login
Content-Type: application/json

{
  "email":"carlos1997704@gmail.com",
  "password":"123456"
}

###create a donor
POST http://localhost:62299/donors
Content-Type: application/json

{
  "name":"Carlos Andres Noreña Vargas",
  "email":"carlos@gmail.com",
  "password":"123456",
  "idType":"National ID",
  "idNumber":"1000897044",
  "phone":"3000000000",
  "address":"Calle 1 # 1-1",
  "city":"Medellin",
  "state":"Antioquia",
  "country":"Colombia",
  "description":"Donante dinero a caridad",
  "blocked":false,
  "adminId":"13691912-bd99-4693-a8e2-55f65c843a73"
}
